/**
 * zh.js — 中文优先输出层
 *
 * 包含：
 *  1. FIELD_LABELS   各领域输出列 → 中文标签
 *  2. DOMAIN_LABELS  领域键 → 中文名称
 *  3. STACK_LABELS   技术栈键 → 中文名称
 *  4. SEVERITY_LABELS 严重度 → 中文
 *  5. ZH_ALIASES     中文术语 → 英文关键词（用于把中文查询扩展到英文语料）
 */

// ---------- 领域中文名 ----------
export const DOMAIN_LABELS = {
  style: '设计风格',
  color: '配色方案',
  chart: '图表类型',
  landing: '落地页模式',
  product: '产品类型',
  ux: 'UX 规范',
  typography: '字体搭配',
  icons: '图标',
  gsap: '动效 (GSAP)',
  react: 'React 性能',
  web: '移动端接口规范',
  'google-fonts': 'Google 字体',
  stack: '技术栈规范',
}

// ---------- 技术栈中文名 ----------
export const STACK_LABELS = {
  react: 'React',
  nextjs: 'Next.js',
  vue: 'Vue',
  svelte: 'Svelte',
  astro: 'Astro',
  swiftui: 'SwiftUI',
  'react-native': 'React Native',
  flutter: 'Flutter',
  nuxtjs: 'Nuxt.js',
  'nuxt-ui': 'Nuxt UI',
  'html-tailwind': 'HTML + Tailwind',
  shadcn: 'shadcn/ui',
  'jetpack-compose': 'Jetpack Compose',
  threejs: 'Three.js',
  angular: 'Angular',
  laravel: 'Laravel',
  javafx: 'JavaFX',
  wpf: 'WPF',
  winui: 'WinUI',
  avalonia: 'Avalonia',
  uno: 'Uno Platform',
  uwp: 'UWP',
}

// ---------- 严重度 / 优先级 ----------
export const SEVERITY_LABELS = {
  Critical: '严重',
  High: '高',
  Medium: '中',
  Low: '低',
}
export const SEVERITY_ORDER = { Critical: 0, High: 1, Medium: 2, Low: 3 }

export const PRIORITY_LABELS = {
  1: '首选',
  2: '次选',
  3: '备选',
}

// ---------- 各领域输出列 → 中文标签 ----------
export const FIELD_LABELS = {
  style: {
    'Style Category': '风格名称',
    Type: '类型',
    Keywords: '关键词',
    'Primary Colors': '主色',
    'Secondary Colors': '辅助色',
    'Effects & Animation': '效果与动效',
    'Best For': '适用场景',
    'Do Not Use For': '不适用场景',
    'Light Mode ✓': '浅色模式',
    'Dark Mode ✓': '深色模式',
    Performance: '性能',
    Accessibility: '无障碍',
    'Mobile-Friendly': '移动端友好',
    'Conversion-Focused': '转化导向',
    'Framework Compatibility': '框架兼容性',
    'Era/Origin': '时代/起源',
    Complexity: '复杂度',
    'AI Prompt Keywords': 'AI 提示词关键词',
    'CSS/Technical Keywords': 'CSS/技术关键词',
    'Implementation Checklist': '实现清单',
    'Design System Variables': '设计系统变量',
  },
  color: {
    'Product Type': '产品类型',
    Primary: '主色',
    'On Primary': '主色前景',
    Secondary: '次色',
    'On Secondary': '次色前景',
    Accent: '强调色(CTA)',
    'On Accent': '强调色前景',
    Background: '背景色',
    Foreground: '前景文字色',
    Card: '卡片色',
    'Card Foreground': '卡片文字色',
    Muted: '弱化色',
    'Muted Foreground': '弱化文字色',
    Border: '边框色',
    Destructive: '危险色',
    'On Destructive': '危险色前景',
    Ring: '焦点环色',
    Notes: '说明',
  },
  chart: {
    'Data Type': '数据类型',
    Keywords: '关键词',
    'Best Chart Type': '最佳图表类型',
    'Secondary Options': '备选图表',
    'When to Use': '适用时机',
    'When NOT to Use': '不适用时机',
    'Data Volume Threshold': '数据量阈值',
    'Color Guidance': '配色指引',
    'Accessibility Grade': '无障碍等级',
    'Accessibility Notes': '无障碍说明',
    'A11y Fallback': '无障碍降级方案',
    'Library Recommendation': '推荐图表库',
    'Interactive Level': '交互级别',
  },
  landing: {
    'Pattern Name': '模式名称',
    Keywords: '关键词',
    'Section Order': '区块顺序',
    'Primary CTA Placement': '主 CTA 位置',
    'Color Strategy': '配色策略',
    'Recommended Effects': '推荐效果',
    'Conversion Optimization': '转化优化',
  },
  product: {
    'Product Type': '产品类型',
    Keywords: '关键词',
    'Primary Style Recommendation': '首选风格',
    'Secondary Styles': '备选风格',
    'Landing Page Pattern': '落地页模式',
    'Dashboard Style (if applicable)': '看板风格',
    'Color Palette Focus': '配色重点',
    'Key Considerations': '关键考量',
  },
  ux: {
    Category: '类别',
    Issue: '问题',
    Platform: '平台',
    Description: '描述',
    Do: '应该',
    "Don't": '避免',
    'Code Example Good': '正确代码示例',
    'Code Example Bad': '错误代码示例',
    Severity: '严重度',
  },
  typography: {
    'Font Pairing Name': '字体搭配名称',
    Category: '类别',
    'Heading Font': '标题字体',
    'Body Font': '正文字体',
    'Mood/Style Keywords': '气质/风格关键词',
    'Best For': '适用场景',
    'Google Fonts URL': 'Google Fonts 链接',
    'CSS Import': 'CSS 导入',
    'Tailwind Config': 'Tailwind 配置',
    Notes: '说明',
  },
  icons: {
    Category: '类别',
    'Icon Name': '图标名称',
    Keywords: '关键词',
    Library: '图标库',
    'Import Code': '导入代码',
    Usage: '用法',
    'Best For': '适用场景',
    Style: '风格',
  },
  gsap: {
    Category: '类别',
    'Intensity Tier': '强度档位',
    Keywords: '关键词',
    Trigger: '触发方式',
    Duration: '时长',
    Easing: '缓动',
    'GSAP Snippet': 'GSAP 代码',
    'Framework Notes': '框架说明',
    Do: '应该',
    "Don't": '避免',
    'Performance Notes': '性能说明',
  },
  react: {
    Category: '类别',
    Issue: '问题',
    Platform: '平台',
    Description: '描述',
    Do: '应该',
    "Don't": '避免',
    'Code Example Good': '正确代码示例',
    'Code Example Bad': '错误代码示例',
    Severity: '严重度',
  },
  web: {
    Category: '类别',
    Issue: '问题',
    Platform: '平台',
    Description: '描述',
    Do: '应该',
    "Don't": '避免',
    'Code Example Good': '正确代码示例',
    'Code Example Bad': '错误代码示例',
    Severity: '严重度',
  },
  'google-fonts': {
    Family: '字体家族',
    Category: '类别',
    Stroke: '笔画风格',
    Classifications: '分类',
    Keywords: '关键词',
    Styles: '字重样式',
    'Variable Axes': '可变轴',
    Subsets: '字符集',
    Designers: '设计师',
    'Popularity Rank': '流行度排名',
    'Google Fonts URL': 'Google Fonts 链接',
  },
  stack: {
    Category: '类别',
    Guideline: '规范',
    Platform: '平台',
    Description: '描述',
    Do: '应该',
    "Don't": '避免',
    'Code Good': '正确代码示例',
    'Code Bad': '错误代码示例',
    Severity: '严重度',
    'Docs URL': '文档链接',
  },
}

/**
 * 将一行记录（原英文列名 → 值）转为中文标签行。
 * 未知列保留原键名（附在括号内），值原样保留。
 * @param {object} row - 原始行
 * @param {string} domain - 领域键
 * @returns {object} 中文标签行
 */
export function localizeRow(row, domain) {
  const labels = FIELD_LABELS[domain] || {}
  const out = {}
  for (const [key, value] of Object.entries(row)) {
    const label = labels[key]
    if (label) out[label] = value
    else out[`${key} (${key})`] = value
  }
  return out
}

// ---------- 中文术语 → 英文关键词 ----------
/**
 * 中文查询扩展词典：把中文产品类型/风格/场景词映射到英文语料关键词，
 * 使 BM25 能命中以英文关键词为主的数据库。
 * 值为数组：全部会作为补充关键词参与检索（每个取前几个即可）。
 */
export const ZH_ALIASES = {
  // ---- 产品类型 ----
  金融: ['fintech', 'finance', 'banking', 'crypto', 'investment'],
  银行: ['fintech', 'banking', 'finance'],
  支付: ['fintech', 'payment', 'checkout'],
  加密货币: ['crypto', 'cryptocurrency', 'blockchain'],
  币圈: ['crypto', 'cryptocurrency'],
  电商: ['ecommerce', 'e-commerce', 'shop', 'store', 'retail'],
  商城: ['ecommerce', 'e-commerce', 'shop', 'store'],
  购物: ['ecommerce', 'shop', 'retail'],
  医疗: ['healthcare', 'medical', 'health', 'clinic'],
  健康: ['healthcare', 'health', 'wellness', 'fitness'],
  美容: ['beauty', 'spa', 'cosmetic'],
  美妆: ['beauty', 'cosmetic', 'makeup'],
  护肤: ['beauty', 'skincare', 'spa'],
  教育: ['education', 'learning', 'elearning', 'course'],
  学习: ['education', 'learning', 'study'],
  在线教育: ['education', 'elearning', 'course'],
  游戏: ['gaming', 'game', 'arcade'],
  社交: ['social', 'social-network', 'community', 'messenger'],
  聊天: ['chat', 'messenger', 'social', 'communication'],
  音乐: ['music', 'audio', 'streaming'],
  视频: ['video', 'streaming', 'entertainment'],
  流媒体: ['streaming', 'video', 'music', 'entertainment'],
  健身: ['fitness', 'workout', 'gym', 'health'],
  运动: ['fitness', 'sport', 'workout'],
  旅游: ['travel', 'trip', 'tourism', 'booking'],
  旅行: ['travel', 'trip', 'tourism'],
  酒店: ['hotel', 'travel', 'booking', 'hospitality'],
  民宿: ['hotel', 'travel', 'booking'],
  餐饮: ['restaurant', 'food', 'dining'],
  餐厅: ['restaurant', 'food', 'dining'],
  美食: ['food', 'restaurant', 'recipe'],
  外卖: ['delivery', 'food', 'restaurant'],
  菜谱: ['recipe', 'food', 'cooking'],
  房地产: ['real estate', 'property', 'housing'],
  房产: ['real estate', 'property'],
  租房: ['real estate', 'rental', 'housing'],
  保险: ['insurance', 'fintech'],
  法律: ['legal', 'law', 'compliance'],
  律师: ['legal', 'law'],
  约会: ['dating', 'social', 'match'],
  婚恋: ['dating', 'wedding'],
  婚礼: ['wedding', 'event'],
  天气: ['weather', 'forecast'],
  睡眠: ['sleep', 'health', 'wellness', 'meditation'],
  冥想: ['meditation', 'wellness', 'health', 'sleep'],
  阅读: ['reading', 'ebook', 'literature', 'book'],
  电子书: ['reading', 'ebook', 'book'],
  播客: ['podcast', 'audio', 'newsletter'],
  新闻: ['news', 'newsletter', 'media'],
  订阅: ['newsletter', 'subscription', 'saas'],
  日记: ['diary', 'journal', 'note'],
  笔记: ['note', 'notes', 'productivity', 'diary'],
  记账: ['tracker', 'finance', 'budget', 'expense'],
  财务: ['finance', 'fintech', 'accounting', 'invoice'],
  发票: ['invoice', 'finance', 'billing'],
  日历: ['calendar', 'productivity', 'schedule'],
  日程: ['calendar', 'schedule', 'productivity'],
  待办: ['todo', 'task', 'productivity', 'tracker'],
  任务: ['task', 'todo', 'project', 'productivity'],
  项目管理: ['project', 'task', 'saas', 'productivity'],
  CRM: ['crm', 'saas', 'sales', 'b2b'],
  客户管理: ['crm', 'saas', 'sales'],
  停车: ['parking', 'transit', 'city'],
  公交: ['transit', 'transportation', 'city'],
  出行: ['transit', 'travel', 'ride', 'transportation'],
  打车: ['ride', 'transit', 'transportation'],
  导航: ['navigation', 'map', 'transit'],
  VPN: ['vpn', 'security', 'privacy'],
  安全: ['security', 'vpn', 'privacy', 'healthcare'],
  隐私: ['privacy', 'security'],
  闹钟: ['alarm', 'timer', 'clock'],
  计时器: ['timer', 'alarm', 'clock'],
  习惯: ['habit', 'tracker', 'productivity', 'routine'],
  打卡: ['habit', 'tracker', 'fitness'],
  生鲜: ['grocery', 'food', 'delivery', 'ecommerce'],
  买菜: ['grocery', 'food', 'delivery'],
  表情包: ['meme', 'social', 'entertainment'],
  衣柜: ['wardrobe', 'fashion', 'lifestyle'],
  穿搭: ['fashion', 'wardrobe', 'beauty'],
  植物: ['plant care', 'gardening', 'lifestyle'],
  养花: ['plant care', 'gardening'],
  单词卡: ['flashcard', 'education', 'learning'],
  背单词: ['flashcard', 'education', 'learning'],
  拼图: ['puzzle', 'gaming', 'entertainment'],
  答题: ['trivia', 'quiz', 'education', 'gaming'],
  摄影: ['photography', 'camera', 'portfolio'],
  相机: ['photography', 'camera'],
  市集: ['marketplace', 'ecommerce', 'freelancer'],
  二手: ['marketplace', 'ecommerce'],
  自由职业: ['freelancer', 'marketplace', 'portfolio'],
  求职: ['career', 'freelancer', 'job'],
  共享办公: ['coworking', 'productivity', 'office'],
  航空: ['airline', 'travel', 'booking'],
  航班: ['airline', 'travel', 'booking'],
  博物馆: ['museum', 'culture', 'event'],
  剧院: ['theater', 'event', 'culture'],
  演出: ['theater', 'event', 'ticket'],
  教堂: ['church', 'non-profit', 'community'],
  非营利: ['non-profit', 'charity', 'community'],
  慈善: ['charity', 'non-profit'],
  幼儿园: ['kindergarten', 'daycare', 'education', 'children'],
  托育: ['daycare', 'kindergarten', 'children'],
  养老: ['senior care', 'healthcare', 'care'],
  宠物: ['veterinary', 'pet', 'care'],
  兽医: ['veterinary', 'pet'],
  花店: ['florist', 'beauty', 'ecommerce', 'local'],
  面包店: ['bakery', 'food', 'restaurant', 'local'],
  烘焙: ['bakery', 'food', 'recipe'],
  精酿: ['brewery', 'food', 'restaurant', 'local'],
  酒吧: ['bar', 'restaurant', 'entertainment'],
  建筑: ['construction', 'real estate', 'b2b'],
  汽车: ['automotive', 'car', 'real estate'],
  物流: ['logistics', 'b2b', 'saas', 'delivery'],
  快递: ['logistics', 'delivery', 'transit'],
  农业: ['agriculture', 'farming', 'logistics'],
  编程培训: ['coding bootcamp', 'education', 'learning', 'course'],
  程序员: ['coding', 'developer', 'developer tool'],
  开发者工具: ['developer tool', 'coding', 'saas', 'b2b'],
  设计工具: ['design tool', 'designer', 'saas', 'creative'],
  智能助手: ['ai', 'assistant', 'tool', 'chat'],
  AI: ['ai', 'chatbot', 'assistant', 'tool', 'saas'],
  人工智能: ['ai', 'chatbot', 'assistant'],
  聊天机器人: ['chatbot', 'ai', 'chat', 'assistant'],
  搜索引擎: ['search', 'tool', 'ai'],
  搜索: ['search', 'tool', 'browse'],
  客服: ['support', 'helpdesk', 'chat', 'saas'],
  工单: ['helpdesk', 'support', 'saas'],
  分析: ['analytics', 'dashboard', 'data', 'metrics'],
  数据: ['data', 'analytics', 'dashboard', 'metrics'],
  看板: ['dashboard', 'analytics', 'data', 'monitor'],
  报表: ['dashboard', 'analytics', 'report', 'data'],
  监控: ['monitor', 'dashboard', 'analytics', 'real-time'],
  实时: ['real-time', 'monitor', 'dashboard', 'live'],
  天气应用: ['weather', 'forecast'],
  播客应用: ['podcast', 'audio'],
  SaaS: ['saas', 'b2b', 'software', 'cloud', 'subscription'],
  软件即服务: ['saas', 'b2b', 'software', 'cloud'],
  企业服务: ['b2b', 'saas', 'enterprise', 'corporate'],
  企业: ['b2b', 'enterprise', 'corporate', 'saas'],
  工具: ['tool', 'utility', 'saas', 'productivity'],
  效率: ['productivity', 'tool', 'utility', 'task'],
  // ---- 行业/场景 ----
  官网: ['landing', 'marketing', 'corporate', 'website'],
  落地页: ['landing', 'marketing', 'conversion', 'hero'],
  营销: ['marketing', 'landing', 'conversion', 'campaign'],
  品牌: ['brand', 'marketing', 'corporate', 'premium'],
  个人主页: ['portfolio', 'personal', 'creative'],
  作品集: ['portfolio', 'creative', 'photography'],
  简历: ['portfolio', 'resume', 'career'],
  博客: ['blog', 'content', 'editorial', 'news'],
  文章: ['blog', 'article', 'content', 'editorial'],
  内容: ['content', 'editorial', 'blog', 'newsletter'],
  社区: ['community', 'social', 'forum'],
  论坛: ['community', 'forum', 'social'],
  商城小程序: ['ecommerce', 'mini-program', 'shop'],
  小程序: ['mini-program', 'app', 'mobile'],
  移动应用: ['mobile', 'app', 'ios', 'android'],
  手机应用: ['mobile', 'app', 'ios', 'android'],
  桌面应用: ['desktop', 'app', 'windows', 'macos'],
  桌面端: ['desktop', 'windows', 'macos'],
  后台: ['admin', 'dashboard', 'saas', 'internal'],
  管理后台: ['admin', 'dashboard', 'internal', 'saas'],
  内部工具: ['internal', 'tool', 'dashboard', 'admin'],
  开发者: ['developer', 'coding', 'tool', 'api'],
  测试: ['testing', 'qa', 'developer'],
  // ---- 风格 ----
  极简: ['minimalism', 'minimal', 'clean', 'simple', 'white space'],
  极简主义: ['minimalism', 'minimal', 'clean'],
  简约: ['minimalism', 'minimal', 'clean', 'simple'],
  毛玻璃: ['glassmorphism', 'glass', 'frosted', 'translucent'],
  玻璃拟态: ['glassmorphism', 'glass', 'frosted'],
  新拟态: ['neumorphism', 'soft ui', 'soft'],
  拟物: ['neumorphism', 'skeuomorphism', 'soft ui'],
  粗野主义: ['brutalism', 'bold', 'raw', 'asymmetric'],
  赛博朋克: ['cyberpunk', 'neon', 'dark', 'futuristic'],
  蒸汽波: ['vaporwave', 'retro', 'neon', 'aesthetic'],
  霓虹: ['neon', 'cyberpunk', 'vibrant', 'dark'],
  暗黑: ['dark mode', 'dark', 'dark-mode'],
  深色: ['dark mode', 'dark', 'dark-mode'],
  浅色: ['light mode', 'light', 'minimal'],
  扁平: ['flat design', 'flat', 'minimal', 'colorful'],
  扁平化: ['flat design', 'flat', 'minimal'],
  波普: ['pop art', 'vibrant', 'playful', 'bold'],
  孟菲斯: ['memphis', 'playful', 'vibrant', 'bold'],
  孟菲斯风格: ['memphis', 'playful', 'vibrant'],
  复古: ['retro', 'vintage', 'classic', 'editorial'],
  怀旧: ['retro', 'vintage', 'nostalgic'],
  日式: ['japanese minimal', 'minimal', 'zen', 'editorial'],
  和风: ['japanese', 'minimal', 'zen'],
  北欧: ['scandinavian', 'minimal', 'clean', 'neutral'],
  瑞士: ['swiss', 'grid', 'minimal', 'typographic'],
  瑞士风格: ['swiss style', 'grid', 'typographic', 'minimal'],
  编辑: ['editorial', 'magazine', 'typographic', 'serif'],
  杂志: ['editorial', 'magazine', 'typographic'],
  手写: ['handwriting', 'playful', 'organic', 'creative'],
  手绘: ['hand-drawn', 'illustration', 'playful', 'organic'],
  插画: ['illustration', 'playful', 'creative', 'hand-drawn'],
  水彩: ['watercolor', 'artistic', 'organic', 'creative'],
  渐变: ['gradient', 'aurora', 'vibrant', 'modern'],
  极光: ['aurora', 'gradient', 'vibrant', 'modern'],
  玻璃: ['glassmorphism', 'glass', 'translucent'],
  '3D': ['3d', 'immersive', 'threejs', 'modern'],
  立体: ['3d', 'immersive', 'depth'],
  拟真: ['realistic', 'skeuomorphism', '3d'],
  企业蓝: ['corporate', 'blue', 'trust', 'professional'],
  深色模式: ['dark mode', 'dark', 'dark-mode'],
  浅色模式: ['light mode', 'light'],
  内容优先: ['content-first', 'editorial', 'minimal', 'reading'],
  沉浸: ['immersive', 'video', 'gaming', '3d'],
  未来: ['futuristic', 'cyberpunk', 'tech', 'modern'],
  科技: ['tech', 'modern', 'futuristic', 'saas'],
  苹果风: ['apple', 'minimal', 'clean', 'premium', 'ios'],
  苹果: ['apple', 'minimal', 'premium', 'ios'],
  谷歌风: ['material', 'google', 'modern', 'clean'],
  Material: ['material design', 'google', 'modern'],
  网格: ['grid', 'bento', 'minimal', 'structured'],
  Bento: ['bento grid', 'grid', 'modern', 'structured'],
  // ---- 气质/情绪 ----
  专业: ['professional', 'corporate', 'clean', 'trust'],
  正式: ['formal', 'professional', 'corporate', 'elegant'],
  优雅: ['elegant', 'luxury', 'premium', 'sophisticated', 'editorial'],
  高端: ['luxury', 'premium', 'elegant', 'sophisticated'],
  奢华: ['luxury', 'premium', 'elegant'],
  精致: ['refined', 'elegant', 'premium', 'sophisticated'],
  活力: ['vibrant', 'playful', 'energetic', 'colorful'],
  活泼: ['playful', 'vibrant', 'fun', 'colorful'],
  有趣: ['playful', 'fun', 'whimsical', 'vibrant'],
  俏皮: ['playful', 'whimsical', 'fun'],
  清新: ['fresh', 'clean', 'light', 'minimal'],
  自然: ['organic', 'nature', 'earthy', 'soft'],
  温暖: ['warm', 'cozy', 'friendly', 'soft'],
  亲和: ['friendly', 'approachable', 'warm', 'human'],
  信任: ['trust', 'professional', 'blue', 'secure'],
  可靠: ['trust', 'reliable', 'professional', 'secure'],
  科技感: ['tech', 'futuristic', 'modern', 'neon'],
  现代: ['modern', 'clean', 'contemporary'],
  时尚: ['fashion', 'trendy', 'modern', 'editorial'],
  潮流: ['trendy', 'fashion', 'vibrant', 'urban'],
  街头: ['urban', 'streetwear', 'bold', 'vibrant'],
  少女: ['feminine', 'soft', 'pastel', 'playful'],
  甜美: ['sweet', 'feminine', 'pastel', 'soft'],
  梦幻: ['dreamy', 'soft', 'pastel', 'whimsical'],
  暗黑系: ['dark', 'gothic', 'moody', 'dramatic'],
  哥特: ['gothic', 'dark', 'dramatic'],
  极客: ['geek', 'tech', 'developer', 'coding'],
  萌系: ['kawaii', 'cute', 'playful', 'colorful'],
  可爱: ['cute', 'kawaii', 'playful'],
  二次元: ['anime', 'manga', 'playful', 'colorful'],
  插画风: ['illustration', 'playful', 'creative'],
  简洁: ['clean', 'minimal', 'simple'],
  大方: ['clean', 'elegant', 'professional'],
  商务: ['business', 'corporate', 'professional', 'b2b'],
  休闲: ['casual', 'friendly', 'relaxed', 'playful'],
  // ---- 设计维度 ----
  响应式: ['responsive', 'mobile-first', 'web'],
  移动优先: ['mobile-first', 'responsive', 'mobile'],
  无障碍: ['accessibility', 'wcag', 'a11y'],
  可访问性: ['accessibility', 'wcag', 'a11y'],
  动效: ['animation', 'motion', 'gsap', 'micro-interaction'],
  动画: ['animation', 'motion', 'gsap'],
  微交互: ['micro-interaction', 'microinteraction', 'animation', 'hover'],
  交互: ['interaction', 'ux', 'micro-interaction', 'feedback'],
  表单: ['form', 'input', 'validation', 'ux'],
  导航: ['navigation', 'nav', 'menu', 'ux'],
  登录: ['login', 'auth', 'signin', 'authentication'],
  注册: ['signup', 'register', 'auth', 'onboarding'],
  认证: ['authentication', 'login', 'auth', 'security'],
  引导: ['onboarding', 'welcome', 'first-run'],
  定价: ['pricing', 'plans', 'subscription', 'saas'],
  付费: ['pricing', 'payment', 'subscription', 'checkout'],
  结账: ['checkout', 'payment', 'cart', 'ecommerce'],
  购物车: ['cart', 'checkout', 'ecommerce'],
  搜索功能: ['search', 'browse', 'filter'],
  筛选: ['filter', 'search', 'browse'],
  列表: ['list', 'virtualize', 'performance', 'mobile'],
  加载: ['loading', 'skeleton', 'progress', 'ux'],
  骨架屏: ['skeleton', 'loading', 'shimmer'],
  空状态: ['empty state', 'zero', 'placeholder'],
  错误状态: ['error state', 'error', 'empty'],
  深色模式适配: ['dark mode', 'dark', 'theme'],
  主题: ['theme', 'dark mode', 'light mode', 'token'],
  设计令牌: ['design token', 'token', 'theme', 'css variables'],
  设计系统: ['design system', 'token', 'component', 'design'],
  组件: ['component', 'design system', 'ui'],
  按钮: ['button', 'component', 'cta', 'interaction'],
  卡片: ['card', 'component', 'dashboard', 'bento'],
  图标: ['icon', 'icons', 'svg'],
  字体: ['typography', 'font', 'typeface'],
  排版: ['typography', 'type', 'font'],
  配色: ['color', 'palette', 'color scheme'],
  调色板: ['color', 'palette'],
  渐变配色: ['gradient', 'color', 'aurora'],
  间距: ['spacing', 'layout', 'grid', 'rhythm'],
  布局: ['layout', 'grid', 'spacing', 'responsive'],
  网格布局: ['grid', 'layout', 'bento'],
  阴影: ['shadow', 'elevation', 'depth', 'neumorphism'],
  圆角: ['border radius', 'rounded', 'radius'],
  性能: ['performance', 'react', 'bundle', 'memo'],
  加载速度: ['performance', 'loading', 'bundle', 'optimization'],
  转化: ['conversion', 'cta', 'landing', 'optimization'],
  留存: ['retention', 'onboarding', 'engagement'],
  图表: ['chart', 'graph', 'visualization', 'dashboard'],
  数据可视化: ['chart', 'data visualization', 'dashboard'],
  趋势图: ['trend', 'chart', 'line chart'],
  漏斗: ['funnel', 'chart', 'conversion'],
  饼图: ['pie', 'chart', 'donut'],
  柱状图: ['bar', 'chart', 'comparison'],
  折线图: ['line', 'trend', 'chart'],
  热力图: ['heatmap', 'chart', 'density'],
  散点图: ['scatter', 'chart', 'correlation'],
  仪表盘: ['dashboard', 'gauge', 'analytics'],
  深色图表: ['dark mode', 'chart', 'color guidance'],
  // ---- 平台/技术栈 ----
  移动端: ['mobile', 'ios', 'android', 'react-native', 'flutter'],
  iOS: ['ios', 'mobile', 'apple', 'swiftui'],
  Android: ['android', 'mobile', 'jetpack compose', 'material'],
  网页: ['web', 'responsive', 'html', 'css'],
  网站: ['web', 'website', 'landing', 'responsive'],
  桌面: ['desktop', 'windows', 'wpf', 'winui', 'javafx'],
  跨平台: ['cross-platform', 'flutter', 'react-native', 'uno'],
  小程序开发: ['mini-program', 'mobile', 'wechat'],
  React: ['react', 'nextjs', 'frontend'],
  Vue: ['vue', 'nuxtjs', 'frontend'],
  前端: ['frontend', 'web', 'react', 'vue', 'html'],
  后端: ['backend', 'api', 'laravel', 'server'],
  全栈: ['fullstack', 'frontend', 'backend'],
  Flutter: ['flutter', 'cross-platform', 'mobile'],
  Swift: ['swiftui', 'ios', 'apple', 'mobile'],
  原生: ['native', 'ios', 'android', 'mobile'],
  控制台: ['console', 'dashboard', 'admin', 'internal'],
  编辑器: ['editor', 'tool', 'developer', 'coding'],
  终端: ['terminal', 'developer', 'cli', 'coding'],
  API: ['api', 'developer', 'tool', 'saas'],
  接口: ['api', 'integration', 'developer'],
  微服务: ['microservice', 'backend', 'saas'],
  云: ['cloud', 'saas', 'b2b'],
  大数据: ['data', 'analytics', 'dashboard', 'big data'],
  物联网: ['iot', 'smart home', 'hardware', 'dashboard'],
  智能家居: ['smart home', 'iot', 'dashboard'],
  可穿戴: ['wearable', 'fitness', 'health', 'mobile'],
  车载: ['automotive', 'car', 'dashboard', 'mobile'],
  电视: ['tv', 'streaming', 'entertainment', 'video'],
  // ---- 情绪/密度 ----
  内容密集: ['content-dense', 'dense', 'dashboard', 'data'],
  宽松: ['spacious', 'minimal', 'whitespace', 'airy'],
  紧凑: ['dense', 'compact', 'dashboard', 'data'],
  大胆: ['bold', 'brutalism', 'vibrant', 'asymmetric'],
  不对称: ['asymmetric', 'brutalism', 'experimental', 'bold'],
  居中: ['centered', 'symmetrical', 'minimal'],
  对称: ['symmetrical', 'centered', 'grid-based'],
  实验: ['experimental', 'brutalism', 'avant-garde', 'creative'],
  前卫: ['avant-garde', 'experimental', 'creative'],
}

/**
 * 将中文查询扩展为「原查询 + 英文关键词」。
 * 命中一个别名时，取其前 2 个英文关键词（控制噪音）。
 * @param {string} query - 原始查询（可为中英混合）
 * @returns {string} 扩展后的查询
 */
export function expandQuery(query) {
  const expanded = []
  for (const [zh, en] of Object.entries(ZH_ALIASES)) {
    if (query.includes(zh)) {
      expanded.push(...en.slice(0, 2))
    }
  }
  if (expanded.length === 0) return query
  return `${query} ${expanded.join(' ')}`
}
